name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy TO GCP
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
    
      - name: Submit Build
        run: gcloud builds submit --tag europe-west2-docker.pkg.dev/echoesai/echoes-web-ui/webui:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy echoes-webui --image europe-west2-docker.pkg.dev/echoesai/echoes-web-ui/webui:latest --region europe-west1 --allow-unauthenticated --project echoesai --max-instances=1